// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlsNPLMoRGGT8wsZtPbn5bB2XKDoqMAZc',
    appId: '1:1059814916512:web:aabb5dbfbeef273385a4c5',
    messagingSenderId: '1059814916512',
    projectId: 'odyssey-a5cd3',
    authDomain: 'odyssey-a5cd3.firebaseapp.com',
    storageBucket: 'odyssey-a5cd3.firebasestorage.app',
    measurementId: 'G-25M0V1BJY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw-kctaC_p1ritePqpgpCaAUfcithJoRE',
    appId: '1:1059814916512:android:aba0ac4bdf4685bd85a4c5',
    messagingSenderId: '1059814916512',
    projectId: 'odyssey-a5cd3',
    storageBucket: 'odyssey-a5cd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk90ILfK1GpWnqVwIF7lxXZ8ouAKSrwmE',
    appId: '1:1059814916512:ios:372ee8a70dd6390285a4c5',
    messagingSenderId: '1059814916512',
    projectId: 'odyssey-a5cd3',
    storageBucket: 'odyssey-a5cd3.firebasestorage.app',
    iosBundleId: 'com.example.gradutionProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk90ILfK1GpWnqVwIF7lxXZ8ouAKSrwmE',
    appId: '1:1059814916512:ios:372ee8a70dd6390285a4c5',
    messagingSenderId: '1059814916512',
    projectId: 'odyssey-a5cd3',
    storageBucket: 'odyssey-a5cd3.firebasestorage.app',
    iosBundleId: 'com.example.gradutionProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlsNPLMoRGGT8wsZtPbn5bB2XKDoqMAZc',
    appId: '1:1059814916512:web:0e509c25a3e1250f85a4c5',
    messagingSenderId: '1059814916512',
    projectId: 'odyssey-a5cd3',
    authDomain: 'odyssey-a5cd3.firebaseapp.com',
    storageBucket: 'odyssey-a5cd3.firebasestorage.app',
    measurementId: 'G-CTJPKQR060',
  );
}
